# Import all serializers from serializers_module for backward compatibility
from .serializers_module import (
    UserSerializer,
    RegisterSerializer,
    LoginSerializer,
    CustomerSerializer,
    BookSerializer,
    CartSerializer,
    CartItemSerializer,
    AddToCartSerializer,
    RatingSerializer,
    CreateRatingSerializer,
    StaffSerializer,
    CreateStaffSerializer,
    ShippingSerializer,
    PaymentSerializer,
    CreatePaymentSerializer,
    OrderSerializer,
    OrderItemSerializer,
    CreateOrderSerializer,
    CreateOrderItemSerializer,
)

__all__ = [
    'UserSerializer',
    'RegisterSerializer',
    'LoginSerializer',
    'CustomerSerializer',
    'BookSerializer',
    'CartSerializer',
    'CartItemSerializer',
    'AddToCartSerializer',
    'RatingSerializer',
    'CreateRatingSerializer',
    'StaffSerializer',
    'CreateStaffSerializer',
    'ShippingSerializer',
    'PaymentSerializer',
    'CreatePaymentSerializer',
    'OrderSerializer',
    'OrderItemSerializer',
    'CreateOrderSerializer',
    'CreateOrderItemSerializer',
]


