# Generated by Django 5.1.1 on 2026-01-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="shipping",
            name="fee",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
