# Generated by Django 5.1.1 on 2026-01-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_order_total_price_alter_shipping_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="email",
            field=models.EmailField(
                default="staff@bookstore.com", max_length=254, unique=True
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="password",
            field=models.CharField(default="123456", max_length=100),
        ),
    ]
